OTC-276: enabling searching not only matched payments etc
openimis/web_app_vb pull request #101
Opened 2021-05-28 13:40 UTC by sniedzielski

TICKET: https://openimis.atlassian.net/browse/OTC-276

changes:
- adding new resources for payment statuses and "RejectedReason" label. 
- enabling looking for another payments, not only paid etc
![otc-276](https://user-images.githubusercontent.com/52816247/119992573-fafb3c00-bfca-11eb-9763-d5a5e09fc5ac.PNG)
![otc-276c](https://user-images.githubusercontent.com/52816247/119992610-08b0c180-bfcb-11eb-838c-d58b1e0d5d8e.PNG)

2021-05-28 15:25 UTC, delcroip commented
@dragos-dobre  add status for cancelled payment

2021-06-01 11:02 UTC, dragos-dobre requested changes

2021-06-01 11:02 UTC, dragos-dobre commented on IMIS_BL/General.vb
> +                dtStatus.Rows.Add(-3, getMessage("T_FAILEDSTATUS"))
Please create a constant list for the PaymentStatus and use it here. Will be easier to understand.

2021-06-01 11:03 UTC, sniedzielski commented on IMIS_BL/General.vb
> +                dtStatus.Rows.Add(-3, getMessage("T_FAILEDSTATUS"))
ok

2021-06-01 13:41 UTC, sniedzielski commented
@dragos-dobre I added static dict with PaymentStatus. I also fixed conflict with OTC-10 merged into develop. You can re-check this PR.

2021-06-01 14:01 UTC, dragos-dobre approved these changes

2021-06-01 14:01 UTC, merged