OTC-402: MV: FSP  District automatically filled with the first option in the field  FSP District
openimis/web_app_vb pull request #128
Opened 2021-10-01 10:36 UTC by hirensoni913

https://openimis.atlassian.net/browse/OTC-402

2021-10-01 11:44 UTC, dragos-dobre requested changes

2021-10-01 11:44 UTC, dragos-dobre commented on IMIS/IMIS.vbproj
> -      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
Please let this in. Will help to set the folder permissions.

2021-10-01 11:44 UTC, dragos-dobre commented on IMIS/web.base.config
> +         connectionString="Data Source=HIREN\MSSQLSERVER01;Initial Catalog=CH_CENTRAL;User ID=sa;Password=sa"
Leave the connection string as default here and use the Web.Debug|Release.config instead to modify the db connection.

2021-10-01 14:02 UTC, hirensoni913 commented on IMIS/IMIS.vbproj
> -      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
Done

2021-10-03 15:26 UTC, dragos-dobre approved these changes

2021-10-03 15:26 UTC, merged