OTC-403: MV: unify the position of Vulnerability field
openimis/web_app_vb pull request #129
Opened 2021-10-01 11:12 UTC by hirensoni913

https://openimis.atlassian.net/browse/OTC-403

2021-10-01 12:33 UTC, dragos-dobre requested changes

2021-10-01 12:33 UTC, dragos-dobre commented on IMIS/IMIS.vbproj
> -      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
Please leave this in.

2021-10-01 14:07 UTC, hirensoni913 commented on IMIS/IMIS.vbproj
> -      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
Done!

2021-10-03 15:28 UTC, dragos-dobre approved these changes

2021-10-03 15:28 UTC, merged