OS-82 Default secret keys warning added for Admin on homepage.
openimis/web_app_vb pull request #144
Opened 2022-02-14 10:24 UTC by wzglinieckisoldevelo

Changes:
* Added hidden field to show alert.
* Added alert for admin if default secret keys were not changed.
* Added labels in resources.

https://openimis.atlassian.net/browse/OS-82

2022-02-15 08:10 UTC, dragos-dobre requested changes

2022-02-15 12:41 UTC, dragos-dobre requested changes

2022-02-15 12:41 UTC, dragos-dobre commented on IMIS/App_GlobalResources/Resource.resx
> +    <value>The following secret keys were left at a default value. Please change it in config file immediately!</value>
Please change to 'For security reasons, please change them in Web.config file. Make sure secret keys are also updated in mobile applications.'.

2022-02-16 07:21 UTC, wzglinieckisoldevelo commented on IMIS/App_GlobalResources/Resource.resx
> +    <value>The following secret keys were left at a default value. Please change it in config file immediately!</value>
Changed. I've also added appropriate caption in lokalise app.

2022-02-24 08:11 UTC, merged