OTC-530: Moving district is now blocked if local pricelists present.
openimis/web_app_vb pull request #158
Opened 2022-04-21 07:42 UTC by wzglinieckisoldevelo

https://openimis.atlassian.net/browse/OTC-530

Changes:
- When moving districts checks for existing local pricelists
- If no local pricelists present, allow to move district
- If they are present, show warning and block the move

2022-04-22 07:00 UTC, delcroip commented
@wzglinieckisoldevelo  Jiri wanted to unlink the PL , can you change your warning to a cconfirmation box  : if ok move AND remove the conflicting pricelist if cancel BLOCK

br

2022-05-05 08:41 UTC, delcroip commented
@still a draft ?

2022-05-18 07:11 UTC, malinowskikam commented on IMIS/MoveLocation.aspx.vb
>              If IsPostBack = True Then Return
These two IF statements can be merged

2022-05-18 07:56 UTC, malinowskikam requested changes
@wzglinieckisoldevelo Please check my comment.

2022-05-18 08:32 UTC, wzglinieckisoldevelo commented on IMIS/MoveLocation.aspx.vb
>              If IsPostBack = True Then Return
Request.Params exist only if IsPostBack is true, so merging would be problematic.

2022-05-18 08:45 UTC, malinowskikam approved these changes

2022-06-08 06:49 UTC, delcroip approved these changes

2022-06-08 06:50 UTC, merged