Nepal Features
openimis/web_app_vb pull request #39
Opened 2020-04-06 11:21 UTC by purusap

Nepal Features

2020-05-19 15:12 UTC, dragos-dobre commented on IMIS/Claim.aspx.vb
> +        'lblGurantee.Visible = Not (Adjustibility = "N")
Why you commented this?

2020-05-19 15:12 UTC, dragos-dobre commented on IMIS/Claim.aspx.vb
> +        'rfGuranteeId.Enabled = (Adjustibility = "M")
Why you commented this?

2020-05-19 15:13 UTC, dragos-dobre commented on IMIS/Claim.aspx
> +                                <td colspan="4" style="color:red;">कृपया यस Claim सँग सम्वन्धित सबै कागजत मोबाईल App अथवा वेबसाईटबाट अनिवार्य अपलोड गर्नु होला।  <asp:DynamicHyperLink id="lnkUploadDoc
The text is hardcoded in Nepalese. Please use resource translation.

2020-05-19 15:40 UTC, dragos-dobre commented on IMIS/Home.aspx
> +            var noticeurl = "<%=System.Configuration.ConfigurationManager.AppSettings("NoticeURL").ToString()%>";
What this URL is meant to do? Also, 'NoticeURL' is not present in web.base.config. If only used in Nepal, I would suggest loading the notice only if NoticeURL is present in the config.

2020-05-19 15:44 UTC, dragos-dobre commented on IMIS/IMIS.Master.vb
> +        ' Get Family List
Can you move the SQL code to IMIS_DAL project and make the necessary links through BL and BI. This follows a layered architecture.

2020-05-19 15:46 UTC, dragos-dobre commented on IMIS/IMIS.Master.vb
> +            If statusCell.Text = "क्रियाशिल" Then
String hardcoded. Please use the language resource.

2020-05-19 15:50 UTC, dragos-dobre commented on IMIS/IMIS.Master.vb
> +    'Private Sub FillProductDetails()
In Nepal you don't display product details in enquiring? We need this in master version.

2020-05-19 15:52 UTC, dragos-dobre commented on IMIS/InsureeProfile.aspx.vb
> +        'RunPageSecurity()
Is this page part of the Profile and authorities? Is this page available to everybody?

2020-05-19 15:53 UTC, dragos-dobre commented on IMIS/InsureeProfile.aspx.vb
> +        Dim NSHID As String
Why NSHID? Is this term generic?

2020-05-19 15:54 UTC, dragos-dobre commented on IMIS/InsureeProfile.aspx.vb
> +    Private Sub BindData(ByVal NSHI As String)
NSHID when called but NSHI here. Not consistent.

2020-05-19 15:54 UTC, dragos-dobre commented on IMIS/InsureeProfile.aspx.vb
> +            If statusCell.Text = "क्रियाशिल" Then
String hardcoded. To be moved to language resource.

2020-05-19 15:57 UTC, dragos-dobre commented on IMIS_DAL/ClaimsDAL.vb
> +        data.params("@ClaimCode", SqlDbType.NVarChar, 10, eClaim.ClaimCode)
Must be changed in DB also. Please create a migration script for this in db repository.

2020-05-24 06:06 UTC, purusap commented on IMIS/InsureeProfile.aspx.vb
> +        'RunPageSecurity()
Yes Available to everybody.

2020-05-24 06:07 UTC, purusap commented on IMIS/Claim.aspx.vb
> +        'lblGurantee.Visible = Not (Adjustibility = "N")
We used GuranteeID for another filed.

2020-05-24 06:07 UTC, purusap commented on IMIS/Claim.aspx.vb
> +        'rfGuranteeId.Enabled = (Adjustibility = "M")
We used GuranteeID for another filed.

2020-05-24 06:41 UTC, purusap commented on IMIS/Home.aspx
> +            var noticeurl = "<%=System.Configuration.ConfigurationManager.AppSettings("NoticeURL").ToString()%>";
Done.

2020-05-24 07:11 UTC, purusap commented on IMIS/Claim.aspx
> +                                <td colspan="4" style="color:red;">कृपया यस Claim सँग सम्वन्धित सबै कागजत मोबाईल App अथवा वेबसाईटबाट अनिवार्य अपलोड गर्नु होला।  <asp:DynamicHyperLink id="lnkUploadDoc
Fixed.

2020-05-24 07:23 UTC, purusap commented on IMIS/IMIS.Master.vb
> +        ' Get Family List
Fixed

2020-05-24 07:44 UTC, purusap commented on IMIS/InsureeProfile.aspx.vb
> +    Private Sub BindData(ByVal NSHI As String)
Fixed.

2020-05-24 07:44 UTC, purusap commented on IMIS/InsureeProfile.aspx.vb
> +            If statusCell.Text = "क्रियाशिल" Then
Fixed.

2020-05-24 07:44 UTC, purusap commented on IMIS/InsureeProfile.aspx.vb
> +        Dim NSHID As String
Fixed.

2020-05-24 07:45 UTC, purusap commented on IMIS/IMIS.Master.vb
> +            If statusCell.Text = "क्रियाशिल" Then
Fixed.

2020-05-24 07:46 UTC, purusap commented on IMIS/IMIS.Master.vb
> +    'Private Sub FillProductDetails()
We don't display product details.

2020-05-24 08:00 UTC, purusap commented on IMIS_DAL/ClaimsDAL.vb
> +        data.params("@ClaimCode", SqlDbType.NVarChar, 10, eClaim.ClaimCode)
Done.

2020-06-08 08:10 UTC, dragos-dobre commented on IMIS/Claim.aspx.vb
> +        'lblGurantee.Visible = Not (Adjustibility = "N")
Please use tblControls to configure the visibility of this field and do not comment it. If commented, it will break other implementations.

2020-06-08 08:11 UTC, dragos-dobre commented on IMIS/Claim.aspx.vb
> +        'rfGuranteeId.Enabled = (Adjustibility = "M")
Please use tblControls to configure the visibility of this field and do not comment it. If commented, it will break other implementations.

2020-06-08 08:12 UTC, dragos-dobre commented on IMIS/Home.aspx
> +            var noticeurl = "<%=System.Configuration.ConfigurationManager.AppSettings("NoticeURL").ToString()%>";
What this URL is meant to do?

2020-06-08 08:15 UTC, dragos-dobre commented on IMIS/IMIS.Master.vb
> +    'Private Sub FillProductDetails()
If you don't use this in Nepal, you need to use a build variant on the code. We can look on this together.

2020-09-03 06:54 UTC, purusap commented on IMIS/Home.aspx
> +            var noticeurl = "<%=System.Configuration.ConfigurationManager.AppSettings("NoticeURL").ToString()%>";
This URL gets notice JSON from another Application (Developed by HIB) and display that in home page.

2020-09-03 07:53 UTC, dragos-dobre commented on IMIS/Home.aspx
> +            var noticeurl = "<%=System.Configuration.ConfigurationManager.AppSettings("NoticeURL").ToString()%>";
This means the code is Nepal specific. We cannot include it in the Master Version.

2020-12-08 13:20 UTC, dragos-dobre requested changes

2020-12-08 13:20 UTC, dragos-dobre commented on IMIS/Claim.aspx
> +<<<<<<< HEAD
@purusap Did you forgot to solve the conflicts?

2020-12-08 13:22 UTC, dragos-dobre requested changes

2020-12-08 13:22 UTC, dragos-dobre commented on IMIS/Home.aspx
> +    <%  If Not System.Configuration.ConfigurationManager.AppSettings("NoticeURL") = Nothing Then  %>
Did you added the NoticeURL in the configuration file?

2020-12-08 13:27 UTC, dragos-dobre commented
@purusap There are still issues to be solved, Please review the remaining items.

2020-12-31 04:03 UTC, purusap commented on IMIS/Claim.aspx
> +<<<<<<< HEAD
Solved.

2020-12-31 04:04 UTC, purusap commented on IMIS/Home.aspx
> +    <%  If Not System.Configuration.ConfigurationManager.AppSettings("NoticeURL") = Nothing Then  %>
Yes

2021-05-01 05:50 UTC, closed without merging