OP-240: Integrate Exact with Master Version
openimis/web_app_vb pull request #52
Opened 2020-08-31 13:15 UTC by dborowiecki

TICKET: [OP-240](https://openimis.atlassian.net/browse/OP-240/)

2020-08-31 20:21 UTC, delcroip commented on IMIS_DAL/PolicyDAL.vb
> +        ElseIf Not ePolicy.PolicyValue Is Nothing And (ePolicy.PolicyStatus Is Nothing Or ePolicy.PolicyStatus <> 4) Then 'When on overviewfamily page, policy value have changed
this will be applied for ePolicy.PolicyStatus = 16 (ready) if the the value is something, on the status 16 a  value should be there because only the payment is missing

2020-09-01 11:21 UTC, dborowiecki commented on IMIS/EnterNewPassword.aspx
> +                    <asp:RequiredFieldValidator ID="rfPassword" runat="server"  ControlToValidate="txtPassword" ErrorMessage='<%$ Resources:Resource, M_WEAKPASSWORD %>'  ValidationGroup="submit" Text
If there is no password entered, displayed error is:

> Please check fields marked with an asterisk (*).

However, if a password that does not meet the requirements is entered (e.g. 4 letters length), 
V_PASSWORDREQUIRED does not provide information why the password is incorrect (message: "Password is required"). I think M_WEAKPASSWORD is more informative in this case. Maybe it would be a good idea to adjust the message content? Let me know if I should change it in some way.

2020-09-01 11:24 UTC, dborowiecki commented on IMIS/User.aspx.vb
> -                If HttpContext.Current.Request.QueryString("r") = 1 Or eUsers.ValidityTo.HasValue Then
Read only mode restored, there is no reason to withdraw it.

2020-09-01 11:24 UTC, dborowiecki commented on IMIS_BL/InsureeBL.cs
> +﻿// 'Copyright (c) 2016-2017 Swiss Agency for Development and Cooperation (SDC)
File wasn't use, removed.

2020-09-01 11:28 UTC, dborowiecki commented on IMIS_DAL/PolicyDAL.vb
> +        ElseIf Not ePolicy.PolicyValue Is Nothing And (ePolicy.PolicyStatus Is Nothing Or ePolicy.PolicyStatus <> 4) Then 'When on overviewfamily page, policy value have changed
I changed the order so that 
`ePolicy.PolicyValue Is Nothing And (ePolicy.PolicyStatus Is Nothing Or ePolicy.PolicyStatus <> 4)`
will not overwrite others statements.

2020-09-03 17:34 UTC, delcroip commented on IMIS/ForgotPassword.aspx
> -                    <asp:RequiredFieldValidator ID="rfPassword" runat="server"  ControlToValidate="txtPassword" ErrorMessage='<%$ Resources:Resource, V_PASSWORDREQUIRED %>'  ValidationGroup="submit"
@dragos-dobre Can you advise ?

2020-09-03 17:35 UTC, delcroip commented on IMIS/EnterNewPassword.aspx
> +                    <asp:RequiredFieldValidator ID="rfPassword" runat="server"  ControlToValidate="txtPassword" ErrorMessage='<%$ Resources:Resource, M_WEAKPASSWORD %>'  ValidationGroup="submit" Text
@dragos-dobre can you advise?

2020-09-08 13:13 UTC, dragos-dobre commented on IMIS/EnterNewPassword.aspx
> +                    <asp:RequiredFieldValidator ID="rfPassword" runat="server"  ControlToValidate="txtPassword" ErrorMessage='<%$ Resources:Resource, M_WEAKPASSWORD %>'  ValidationGroup="submit" Text
The password has to comply with the RFC IMIS_SDV-01_Increase_password_strenght_1.0 which defines the message to be displayed. For more information, check the password edition in User form.

2020-09-08 13:14 UTC, dragos-dobre commented on IMIS/ForgotPassword.aspx
> -                    <asp:RequiredFieldValidator ID="rfPassword" runat="server"  ControlToValidate="txtPassword" ErrorMessage='<%$ Resources:Resource, V_PASSWORDREQUIRED %>'  ValidationGroup="submit"
Check message and constraints as in User form.

2020-09-08 13:16 UTC, dragos-dobre commented on IMIS/EnterNewPassword.aspx
> +                    <asp:RequiredFieldValidator ID="rfPassword" runat="server"  ControlToValidate="txtPassword" ErrorMessage='<%$ Resources:Resource, M_WEAKPASSWORD %>'  ValidationGroup="submit" Text
It seems the password requirements are validated after entering the username and password in MV version. So, you can let 'Please check fields marked with an asterisk (*)' if username or password are empty.

2020-09-08 14:36 UTC, dragos-dobre requested changes

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/Claim.aspx.vb
> +                txtCLAIMCODEData.Text = "@" + eClaim.ClaimCode
The '@' string should not be hardcoded. Can this be added as a parameter in Web.Config? It also helpful for Nepal which add 'R' if they resubmit a claim, so it is easier to configure and remember if it is in the configuration file. 
Don't remember this functionality in Claims App but if it is there, then the param should be put in the DB tblDefaults to be shared between components.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/ClaimAdministrator.aspx.vb
> +    Private Function AdiminExists()
Correct function name.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/FindClaims.aspx.vb
> +Imports System.Web.Script.Serialization
I this only this import as new. Is it used?

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/IMIS.Master.cs
> +﻿// 'Copyright (c) 2016-2017 Swiss Agency for Development and Cooperation (SDC)
This is a C# source code. Is it used somewhere? Can be combined with VB?

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/IMIS.vbproj
> -    <Content Include="Web.config">
Web.config is part of the content to be published.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/IMISExtracts.aspx.vb
> +                str = imisgen.getMessage("M_EXTR_PHONEOK") & "<br />Task completed in " & TimeElapsed & " Hours"
Message to be added in resource file and not hardcoded.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/IMISExtracts.aspx.vb
> +                str = imisgen.getMessage("M_EXTR_PHONENOK") & "<br />Task completed in " & TimeElapsed & " Hours"
Message to be added in resource file and not hardcoded.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/IMISExtracts.aspx.vb
> +                imisgen.Alert(str, pnlButtons, alertPopupTitle:="IMIS")
'IMIS' to be added in resource file and not hardcoded. To be changed to 'openIMIS'.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS/Role.aspx
> +              console.log(EventTarget.target);
Debug log to be removed.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS_DAL/PaymentDAL.vb.txt
> +Public Function MatchedPayment(ByVal PaymentID As Integer) As DataTable
This is a txt file. It should be removed.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS_DAL/UserRoleDALvb.vb
> +        Dim strSQL As String = ""
This class and function does nothing. Even the class/file name is not standard. It should be removed.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS_DAL/tblClaimItems.vb
> +    Public RejectionReason As Integer
Is it normal this table class is in IMIS_DAL and not in IMIS_EN?

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS_DAL/tblClaimServices.vb
> +    Public RejectionReason As Integer
Is it normal this table class is in IMIS_DAL and not in IMIS_EN?

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS_DAL/web.Debug.config
> +<?xml version="1.0" encoding="utf-8"?>
This is not needed here. To be removed.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS_DAL/web.Release.config
> +<?xml version="1.0" encoding="utf-8"?>
This is not needed here. To be removed.

2020-09-08 14:36 UTC, dragos-dobre commented on IMIS_DAL/web.config
> +﻿<?xml version="1.0"?>
We don't have web.config in MV. Are you sure it is in TZ version? I propose to remove it.

2020-09-11 08:54 UTC, dragos-dobre approved these changes

2020-09-11 11:10 UTC, druchniewicz commented on IMIS/ClaimAdministrator.aspx.vb
> +    Private Function AdiminExists()
Corrected

2020-09-11 11:11 UTC, druchniewicz commented on IMIS/FindClaims.aspx.vb
> +Imports System.Web.Script.Serialization
Not used. Removed

2020-09-11 11:11 UTC, druchniewicz commented on IMIS/IMIS.Master.cs
> +﻿// 'Copyright (c) 2016-2017 Swiss Agency for Development and Cooperation (SDC)
Unnecessary file. Removed

2020-09-11 11:11 UTC, druchniewicz commented on IMIS/IMIS.vbproj
> -    <Content Include="Web.config">
Restored to <Content>

2020-09-11 11:12 UTC, druchniewicz commented on IMIS/IMISExtracts.aspx.vb
> +                str = imisgen.getMessage("M_EXTR_PHONEOK") & "<br />Task completed in " & TimeElapsed & " Hours"
Extracted to resource file

2020-09-11 11:12 UTC, druchniewicz commented on IMIS/IMISExtracts.aspx.vb
> +                str = imisgen.getMessage("M_EXTR_PHONENOK") & "<br />Task completed in " & TimeElapsed & " Hours"
Extracted to resource file

2020-09-11 11:12 UTC, druchniewicz commented on IMIS/IMISExtracts.aspx.vb
> +                imisgen.Alert(str, pnlButtons, alertPopupTitle:="IMIS")
Extracted to resource file and changed to openIMIS

2020-09-11 11:12 UTC, druchniewicz commented on IMIS/Role.aspx
> +              console.log(EventTarget.target);
Removed

2020-09-11 11:12 UTC, druchniewicz commented on IMIS_DAL/PaymentDAL.vb.txt
> +Public Function MatchedPayment(ByVal PaymentID As Integer) As DataTable
Removed

2020-09-11 11:12 UTC, druchniewicz commented on IMIS_DAL/UserRoleDALvb.vb
> +        Dim strSQL As String = ""
Removed

2020-09-14 07:42 UTC, dragos-dobre approved these changes

2020-09-14 07:45 UTC, delcroip approved these changes

2020-09-14 07:45 UTC, merged