OTC-70: RFC  103  Report Overview of Commissions
openimis/web_app_vb pull request #55
Opened 2020-09-06 22:11 UTC by druchniewicz

Related ticket: https://openimis.atlassian.net/browse/OTC-70

2020-09-07 13:46 UTC, dragos-dobre requested changes

2020-09-07 13:46 UTC, dragos-dobre commented on IMIS/Reports.aspx.vb
> +        scopesList.DataSource = reports.GetReportScope()
There is already the ddlScope select. I would suggest change the name or use the same ddlScope select for this report.

2020-09-07 13:46 UTC, dragos-dobre commented on IMIS/Reports.aspx.vb
> +            IMIS_EN.eReports.Scope = 0
Can't this be `IMIS_EN.eReports.Scope=Val(scopesList.SelectedValue)` and remove the 2 ifs?

2020-09-07 13:46 UTC, dragos-dobre commented on IMIS/Reports.aspx.vb
> +            IMIS_EN.eReports.Mode = 0
Can't this be `IMIS_EN.eReports.Mode=Val(ddlMode.SelectedValue)` and remove the 2 ifs?

2020-09-21 11:32 UTC, dragos-dobre requested changes

2020-09-22 10:15 UTC, dragos-dobre approved these changes

2020-09-22 10:15 UTC, dragos-dobre commented
@druchniewicz Can you solve the conflicting files?

2020-09-22 22:38 UTC, druchniewicz commented
resolved

2020-09-23 09:06 UTC, merged