OTC-146: Added CheckConfiguration escape procedure
openimis/web_app_vb pull request #65
Opened 2020-10-18 15:15 UTC by dborowiecki

TICKET: [OTC-146](https://openimis.atlassian.net/browse/OTC-146)

2020-10-19 14:32 UTC, dragos-dobre requested changes

2020-10-19 14:32 UTC, dragos-dobre commented on IMIS_BL/EscapeBL.vb
> -'
Please do not remove the copyright.

2020-10-19 14:32 UTC, dragos-dobre commented on IMIS_BL/EscapeBL.vb
> +#If CHF Then
Did you defined the Configurations for CHF?

2020-10-19 14:32 UTC, dragos-dobre commented on IMIS/Home.aspx.vb
> +            If Not txtCONFIGISSUE.Text.Equals("") Then
We should display this check only for Users that has rights to Add/Edit/Delete/Duplicate Products.

2020-10-19 14:32 UTC, dragos-dobre commented
Please finish first the WebApp bugs and then get back to this.

2020-10-26 12:12 UTC, dborowiecki commented on IMIS_BL/EscapeBL.vb
> -'
Restored

2020-10-26 12:12 UTC, dborowiecki commented on IMIS_BL/EscapeBL.vb
> +#If CHF Then
I added new property groups to IMIS_BL/IMIS_BL.vbproj

2020-10-26 12:12 UTC, dborowiecki commented on IMIS/Home.aspx.vb
> +            If Not txtCONFIGISSUE.Text.Equals("") Then
I added Dictionary argument to the CheckConfiguration function. I think it will be easy to customize the configuration check in future. In this way, the only change in the code outside Escape class would be adding another key. Let me know if this solution is flexible enough.

2020-11-02 08:37 UTC, dragos-dobre requested changes

2020-11-02 08:37 UTC, dragos-dobre commented on IMIS_BL/IMIS_BL.vbproj
> +    <DefineDebug>false</DefineDebug>
For testing, should we have also debug true? Please create 2 configurations for each implementation: BEPHARelease and BEPHADebug. Same for CHF. 
Also, the configuration is chosen usually from VS for all projects (aka solution). Should we have these configurations in all projects?

2020-11-02 08:37 UTC, dragos-dobre commented on IMIS/Home.aspx.vb
> +            If Not txtCONFIGISSUE.Text.Equals("") Then
Good solution.

2020-11-02 16:34 UTC, dborowiecki commented on IMIS_BL/IMIS_BL.vbproj
> +    <DefineDebug>false</DefineDebug>
@dragos-dobre I added implementation specific solution configs, so now build can be choosen as in picture. 
![obraz](https://user-images.githubusercontent.com/32633751/97893216-46998000-1d31-11eb-91a6-4b91cd1a148d.png)

2020-11-03 07:45 UTC, dragos-dobre approved these changes

2020-11-03 07:45 UTC, dragos-dobre commented
@dborowiecki Can you fix the conflicting files? Thanks.

2020-11-03 07:49 UTC, dborowiecki commented
> @dborowiecki Can you fix the conflicting files? Thanks.
@dragos-dobre Conflict resolved

2020-11-03 08:04 UTC, merged