OTC-108: It is possible to run IMIS Claims only with on-line initialization
openimis/web_app_vb pull request #83
Opened 2021-03-02 15:13 UTC by malinowskikam

changes:
-Added claim admins info to phone extract

https://openimis.atlassian.net/browse/OTC-108

2021-03-10 09:27 UTC, dragos-dobre requested changes

2021-03-10 09:27 UTC, dragos-dobre commented on IMIS_BL/IMISExtractsBL.vb
> +        sSQL = "CREATE TABLE tblAdministrators([Code] Text, [Name] Text)"
Please name this table as tblClaimAdmin as in SQL Server.

2021-03-11 09:16 UTC, malinowskikam commented on IMIS_BL/IMISExtractsBL.vb
> +        sSQL = "CREATE TABLE tblAdministrators([Code] Text, [Name] Text)"
I renamed the table.

2021-03-11 17:22 UTC, dragos-dobre approved these changes

2021-03-11 17:22 UTC, merged