OTC-10: Capitation Payment Report use data from tblCapitationPayment
openimis/web_app_vb pull request #87
Opened 2021-03-29 13:56 UTC by dborowiecki

Part of [OTC-10](https://openimis.atlassian.net/browse/OTC-10)

Procedure uspSSRSCapitationPayment is replaced with uspSSRSRetrieveCapitationPaymentReportData. Before report is generated, it is checked whether the batch run has been executed for given period and location.

2021-03-30 15:46 UTC, dragos-dobre requested changes

2021-03-30 15:46 UTC, dragos-dobre commented on IMIS/App_GlobalResources/Resource.resx
> +	<data name="M_CAPITATION_PAYMENT_NO_BATCH_RUN" xml:space="preserve">
Are these entries added to Lokalize?

2021-03-31 09:07 UTC, dragos-dobre commented
I will wait for the call of the batch to modular before merging to develop.

2021-04-08 09:49 UTC, dborowiecki commented
@dragos-dobre I've added calling modular batch process, can you review?

2021-04-09 08:41 UTC, dragos-dobre requested changes

2021-04-09 08:41 UTC, dragos-dobre commented on IMIS/ProcessBatches.aspx.vb
> +                Response.Redirect("Report.aspx?r=ca&tid=18")
tid is used for getting back to reports.aspx. As the capitation report is not in the report list, I don't think we need to add it here. Please remove.

2021-04-09 08:41 UTC, dragos-dobre commented on IMIS/Reports.aspx.vb
>                  url = "Report.aspx?r=rp&tid=19"
As you removed the cap rep, shouldn't you change the tid to 18 to match SelectedValueID? I don't understand why Exact didn't concat url with SelectedValueID.

2021-04-09 09:57 UTC, dborowiecki commented on IMIS/ProcessBatches.aspx.vb
> +                Response.Redirect("Report.aspx?r=ca&tid=18")
tid removed from redireciton.

2021-04-09 09:59 UTC, dborowiecki commented on IMIS/Reports.aspx.vb
>                  url = "Report.aspx?r=rp&tid=19"
You're right, I changed tids for every report in which SelectedValueID has changed.

2021-06-01 10:57 UTC, dragos-dobre approved these changes

2021-06-01 10:57 UTC, merged