OTC-160: fixed bug with restore after saving new claim
openimis/web_app_vb pull request #89
Opened 2021-04-02 11:57 UTC by sniedzielski

TICKET: https://openimis.atlassian.net/browse/OTC-160

In that PR I want to fix bug described in that ticket. Now after my fixes there is no error when user want to restore claim after saving new claim. The error was due to different URL structure after saving new claim (comparing to page when we enter to claim details)

![pr_OTC-160](https://user-images.githubusercontent.com/52816247/113413501-255dbe00-93bb-11eb-86c2-7fa9d3666b9f.PNG)

2021-04-06 14:39 UTC, dragos-dobre requested changes

2021-04-06 14:39 UTC, dragos-dobre commented on IMIS/Claim.aspx.vb
> +            'OTC-160: Restoring claim doesn't work just after saving a new claim'
No need to add comment about the ticket. After approving this, there will be no issue. This comment is part of the PR saying what is fixing.

2021-04-06 14:39 UTC, dragos-dobre commented on IMIS_BI/ClaimBI.vb
> +        'OTC-160: Restoring claim doesn't work just after saving a new claim'
Please remove this comment.

2021-04-06 14:39 UTC, dragos-dobre commented on IMIS_BL/ClaimsBL.vb
> +        'OTC-160: Restoring claim doesn't work just after saving a new claim'
Please remove this comment.

2021-04-06 14:39 UTC, dragos-dobre commented on IMIS_DAL/ClaimsDAL.vb
> +        'OTC-160: Restoring claim doesn't work just after saving a new claim'
Please remove this comment.

2021-04-06 14:44 UTC, sniedzielski commented on IMIS/Claim.aspx.vb
> +            'OTC-160: Restoring claim doesn't work just after saving a new claim'
Ok. I will remove comment.

2021-04-07 06:57 UTC, sniedzielski commented
@dragos-dobre I removed comments related to the ticket.

2021-04-07 07:11 UTC, dragos-dobre commented on IMIS_BL/ClaimsBL.vb
> +        Return Claim.GetClaimUUIDByClaimCode(ClaimCode).Rows(0).Item(0)
What will this return if no Claim is found for the ClaimCode?

2021-04-07 07:18 UTC, sniedzielski commented on IMIS_BL/ClaimsBL.vb
> +        Return Claim.GetClaimUUIDByClaimCode(ClaimCode).Rows(0).Item(0)
It might be NULL - I will check this. I reused logic for that function from "GetClaimUUIDByID" and "GetClaimIdByUUID" where similar approach is used with .Rows(0).Item(0).

2021-04-07 07:26 UTC, sniedzielski commented on IMIS_BL/ClaimsBL.vb
> +        Return Claim.GetClaimUUIDByClaimCode(ClaimCode).Rows(0).Item(0)
Exception thrown: 'System.IndexOutOfRangeException' in System.Data.dll - And then I will fix this.

2021-04-07 08:34 UTC, sniedzielski commented
@dragos-dobre I updated PR by fixing processing return of no claims in ClaimBL.vb.

2021-04-07 08:43 UTC, dragos-dobre approved these changes

2021-04-07 08:43 UTC, merged