OTC-248: USERS CANT ADD SERVICE CODE UNDER CLAIM - HEALTH FACILITY CLAIMS
openimis/web_app_vb pull request #94
Opened 2021-04-26 09:45 UTC by malinowskikam

Changes:
- Changed B_ADD_Click not to reference current session to generate cleared rows, instead resused the ServiceItemGridBinding call.

[https://openimis.atlassian.net/browse/OTC-248](
https://openimis.atlassian.net/browse/OTC-248)

2021-04-26 11:41 UTC, dragos-dobre requested changes

2021-04-26 11:41 UTC, dragos-dobre commented on IMIS/Claim.aspx.vb
> +            ServiceItemGridBinding()
This method is taking the items and services based on ClaimID. It is loaded when you load an existing claim for edit. Did you tried by opening a claim and pressing add button?

2021-04-27 07:30 UTC, malinowskikam commented on IMIS/Claim.aspx.vb
> +            ServiceItemGridBinding()
When you click the `add` button the page is loaded in `PostBack` mode, and the whole page_load procedure is skipped, meaning that the ClaimUUID in the url is ignored and the `ServiceItemGridBinding` procedure is executing in a clean state.

This line skips the load:
[https://github.com/openimis/web_app_vb/blob/ab5f17bc8073a67287f56ea96ed089d3af09df22/IMIS/Claim.aspx.vb#L67](https://github.com/openimis/web_app_vb/blob/ab5f17bc8073a67287f56ea96ed089d3af09df22/IMIS/Claim.aspx.vb#L67)

2021-04-27 07:31 UTC, dragos-dobre approved these changes

2021-04-27 07:31 UTC, merged